/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daniel Farias
 */
public class CalculadoraDaniel extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraDaniel
     */
    public CalculadoraDaniel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoSoma1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        NomeCalculadora = new javax.swing.JLabel();
        campoResultado = new javax.swing.JTextField();
        campoNumero1 = new javax.swing.JTextField();
        BotaoSoma = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoNumero2 = new javax.swing.JTextField();
        BotaoDivisao = new javax.swing.JButton();
        BotaoMultiplicacao = new javax.swing.JButton();
        BotaoSubtracao = new javax.swing.JButton();

        BotaoSoma1.setFont(new java.awt.Font("Goudy Stout", 0, 18)); // NOI18N
        BotaoSoma1.setText("SOMA");
        BotaoSoma1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.black));
        BotaoSoma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSoma1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 40, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        NomeCalculadora.setFont(new java.awt.Font("Goudy Stout", 0, 20)); // NOI18N
        NomeCalculadora.setForeground(new java.awt.Color(255, 255, 255));
        NomeCalculadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeCalculadora.setText("CALCULADORA");
        NomeCalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        campoResultado.setBackground(new java.awt.Color(192, 192, 193));
        campoResultado.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        campoResultado.setForeground(new java.awt.Color(255, 255, 255));
        campoResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoResultado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        campoResultado.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        campoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoResultadoActionPerformed(evt);
            }
        });

        campoNumero1.setBackground(new java.awt.Color(192, 192, 193));
        campoNumero1.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        campoNumero1.setForeground(new java.awt.Color(255, 255, 255));
        campoNumero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoNumero1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        campoNumero1.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        campoNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumero1ActionPerformed(evt);
            }
        });

        BotaoSoma.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        BotaoSoma.setText("+");
        BotaoSoma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.black));
        BotaoSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSomaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Goudy Stout", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESULTADO:");

        campoNumero2.setBackground(new java.awt.Color(192, 192, 193));
        campoNumero2.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        campoNumero2.setForeground(new java.awt.Color(255, 255, 255));
        campoNumero2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoNumero2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        campoNumero2.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        campoNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumero2ActionPerformed(evt);
            }
        });

        BotaoDivisao.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        BotaoDivisao.setText("/");
        BotaoDivisao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.black));
        BotaoDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDivisaoActionPerformed(evt);
            }
        });

        BotaoMultiplicacao.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        BotaoMultiplicacao.setText("x");
        BotaoMultiplicacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.black));
        BotaoMultiplicacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMultiplicacaoActionPerformed(evt);
            }
        });

        BotaoSubtracao.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        BotaoSubtracao.setText("-");
        BotaoSubtracao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.black));
        BotaoSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSubtracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(campoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BotaoSoma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotaoDivisao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotaoMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotaoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(NomeCalculadora))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel2)))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoResultado)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(NomeCalculadora)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoResultadoActionPerformed

    private void campoNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumero1ActionPerformed

    private void campoNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumero2ActionPerformed

    private void BotaoSoma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSoma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoSoma1ActionPerformed

    private void BotaoDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDivisaoActionPerformed
        String numero1STR = campoNumero1.getText();
        double numero1Double = Double.parseDouble(numero1STR);
        String numero2STR = campoNumero2.getText();
        double numero2Double = Double.parseDouble(numero2STR);
        double resultadoDivisao = numero1Double / numero2Double;
        String resultadoDivisaoSTR = Double.toString(resultadoDivisao);
        campoResultado.setText(resultadoDivisaoSTR);
        campoNumero1.setText(" ");
        campoNumero2.setText(" ");
    }//GEN-LAST:event_BotaoDivisaoActionPerformed

    private void BotaoSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSomaActionPerformed
        String numero1STR = campoNumero1.getText();
        double numero1Double = Double.parseDouble(numero1STR);
        String numero2STR = campoNumero2.getText();
        double numero2Double = Double.parseDouble(numero2STR);
        double resultadoSoma = numero1Double + numero2Double;
        String resultadoSomaSTR = Double.toString(resultadoSoma);
        campoResultado.setText(resultadoSomaSTR);
        campoNumero1.setText(" ");
        campoNumero2.setText(" ");
    }//GEN-LAST:event_BotaoSomaActionPerformed

    private void BotaoSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSubtracaoActionPerformed
        String numero1STR = campoNumero1.getText();
        double numero1Double = Double.parseDouble(numero1STR);
        String numero2STR = campoNumero2.getText();
        double numero2Double = Double.parseDouble(numero2STR);
        double resultadoSubtracao = numero1Double - numero2Double;
        String resultadoSubtracaoSTR = Double.toString(resultadoSubtracao);
        campoResultado.setText(resultadoSubtracaoSTR);
        campoNumero1.setText(" ");
        campoNumero2.setText(" ");
    }//GEN-LAST:event_BotaoSubtracaoActionPerformed

    private void BotaoMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMultiplicacaoActionPerformed
        String numero1STR = campoNumero1.getText();
        double numero1Double = Double.parseDouble(numero1STR);
        String numero2STR = campoNumero2.getText();
        double numero2Double = Double.parseDouble(numero2STR);
        double resultadoMultiplicacao = numero1Double * numero2Double;
        String resultadoMultiplicacaoSTR = Double.toString(resultadoMultiplicacao);
        campoResultado.setText(resultadoMultiplicacaoSTR);
        campoNumero1.setText(" ");
        campoNumero2.setText(" ");
    }//GEN-LAST:event_BotaoMultiplicacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDaniel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDaniel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDaniel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDaniel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraDaniel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoDivisao;
    private javax.swing.JButton BotaoMultiplicacao;
    private javax.swing.JButton BotaoSoma;
    private javax.swing.JButton BotaoSoma1;
    private javax.swing.JButton BotaoSubtracao;
    private javax.swing.JLabel NomeCalculadora;
    private javax.swing.JTextField campoNumero1;
    private javax.swing.JTextField campoNumero2;
    private javax.swing.JTextField campoResultado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
